1)
  1. SELECT UNIQUE NAME FROM COUNTRY WHERE NAME LIKE 'C%' OR NAME LIKE 'D%';
  2. SELECT NAME FROM COUNTRY WHERE GDP > .15 AND YEAR = '2011';
  3. SELECT UNIQUE REGION FROM COUNTRY;
  4. SELECT NAME FROM COUNTRY WHERE POPULATION < 1000000 AND YEAR = '2011';
  5. SELECT NAME FROM COUNTRY WHERE REGION = 'Europe' AND AREA > 100000 AND YEAR = '2005' ORDER BY GDP DESC;

2)
  1. SELECT COUNT (NAME) FROM COUNTRY WHERE GDP > .15 AND YEAR = '2005';
 --This is not correct english. For each year,...
  2. SELECT YEAR , COUNT(NAME) AS NUMBER_COUNTRIES, SUM(POPULATION) AS TOTAL_POPULATION, ( (SUM(POPULATION) ) / (COUNT(NAME) ) ) AS AVE_POPULATION , SUM(GDP) AS TOTAL_GDP FROM COUNTRY WHERE REGION = 'Europe' GROUP BY YEAR ORDER BY YEAR DESC;
  3. SELECT A.REGION FROM COUNTRY A WHERE A.YEAR = '2005' GROUP BY A.REGION HAVING COUNT(*) > 4 AND SUM(A.POPULATION) > 45000000;
  4. SELECT YEAR , SUM ((POPULATION /AREA )) AS DENSITY FROM COUNTRY WHERE REGION = 'Europe' GROUP BY YEAR  ORDER BY YEAR DESC;

3)
 -- This takes a little while to figure out what it is asking. It would be more clear if find names of regions and the area of these regions with.. bc name is a field in the table
  1. SELECT A.REGION , SUM(A.AREA) AS TOTAL_AREA FROM COUNTRY A WHERE A.YEAR = '2002' GROUP BY A.REGION HAVING SUM(A.AREA) > (SELECT SUM(B.AREA) FROM COUNTRY B WHERE B.YEAR = '2002' AND B.REGION = 'Middle East');   1
  2
  3. SELECT A.NAME FROM COUNTRY A WHERE A.YEAR = '2006' AND A.REGION = 'Europe' AND A.POPULATION > (SELECT B.POPULATION FROM COUNTRY B WHERE A.YEAR = B.YEAR AND B.NAME = 'Spain');
  4. SELECT A.NAME FROM COUNTRY A WHERE A.YEAR ='2008' AND A.AREA NOT IN (SELECT B.AREA FROM COUNTRY B , COUNTRY C WHERE B.YEAR = C.YEAR AND B.YEAR = '2008' AND B.AREA > C.AREA);


4)
  1.  DELETE FROM COUNTRY WHERE GDP = 0;
  2.  UPDATE COUNTRY SET AREA = 35000 WHERE NAME = 'Belgium';
  3.  UPDATE COUNTRY SET AREA = (AREA * 1.3) WHERE NAME = 'Peru';

-- CAN WE HAVE MORE THAN ONE STATEMENT?
  4? UPDATE COUNTRY A SET  A.POPULATION = (A.POPULATION + (SELECT B.POPULATION FROM COUNTRY B WHERE B.NAME = 'Hong Kong' AND A.YEAR = B.YEAR))
                        A.AREA = (A.AREA + (SELECT B.AREA FROM COUNTRY B WHERE B.NAME = 'Hong Kong' AND A.YEAR = B.YEAR ))
                        A.GDP = (B.GDP + (SELECT B.GDP FROM COUNTRY B WHERE B.NAME = 'Hong Kong' AND A.YEAR = B.YEAR))
                        WHERE A.NAME = 'China' AND YEAR > 1997;

     DELETE FROM COUNTRY WHERE NAME = 'Hong Kong' AND YEAR > 1997;

5)
  1.

  2. CREATE INDEX POP_INDEX ON COUNTRY (POPULATION);
  3. CREATE VIEW COUNTRY_VIEW AS SELECT REGION, POPULATION, AREA FROM COUNTRY;



FOR 5:1.
  CREATE INDEX POPULATION_RANGE ON COUNTRY (AREA)
     GLOBAL PARTITION BY RANGE (AREA)
        (PARTITION p1 VALUES LESS THAN (10000),
         PARTITION p2 VALUES LESS THAN (250000),
         PARTITION p3 VALUES LESS THAN (MAXVALUE));
