CREATE TYPE PERSON AS OBJECT (
  NAME VARCHAR2(30),
  ADDRESS VARCHAR2(30),
  PHONE NUMBER,
  SSN NUMBER
) NOT FINAL;


CREATE TYPE EMPLOYEE UNDER PERSON (
  SALARY NUMBER,
  SHIFT NUMBER,
);

CREATE TYPE PILOT UNDER PERSON (
  RESTR VARCHAR2,
  LIC_NUM NUMBER
);


CREATE TYPE OWNER AS OBJECT (


)

CREATE TYPE CORPORATION AS OBJECT (
  NAME VARCHAR2(30),
  ADDRESS VARCHAR2(30),
  PHONE NUMBER
);


CREATE TABLE PERSONS OF PERSON (
PRIMANY KEY(SSN) );

INSERT INTO PERSONS VALUES PERSON('MARK', '101 PLESANT ST', 123-123-1234, 123-12-1234);

CREATE TABLE EMPLOYEES OF EMPLOYEE ( );

INSERT INTO EMPLOYEES VALUES ('BOB', 'ADDRESS', 123-123-1234, 123-12-1234, 50000, 1);

CREATE TABLE PILOTS OF PILOT ();

INSERT INTO PILOTS VALUES ('PAUL', 'ADDRESS', 123-123-1234, 123-12-1234, 'RESTR', 1)


CREATE TABLE CORPORATIONS OF CORPORATION();