/home/mcgu0156/Desktop/5708/5708/lab3/lab2.sql

--Part A

CREATE TABLE movie08 (id INTEGER NOT NULL, title VARCHAR(100), yr DECIMAL(4), score FLOAT,  votes INTEGER, director VARCHAR(100), PRIMARY KEY (id) );

INSERT INTO movie08	SELECT * FROM movie	COMMIT;

SELECT TABLE_NAME, GRANTOR, GRANTEE, PRIVILEGE, GRANTABLE FROM ALL_TAB_PRIVS WHERE GRANTOR=’’;
